library(readr)
library(R.matlab)
library(dplyr)
library(purrr)
library(plyr)
library(lubridate)
library(zoo)
Ramp_wl_fast <- read_csv("~/RStudioProjects/still_github/cleaned_files/cleaned_files/Ramp_wl_fast.csv")
Ramp_wl_fast_mat = readMat("~/RStudioProjects/still_github/RStudio_wd_Can_fp/Ramp_wl_fast.mat")

head(Ramp_wl_fast_mat$SR.DAC.3.Drehzahl.Lenkrad......................................)
tail(Ramp_wl_fast_mat$SR.DAC.3.Drehzahl.Lenkrad......................................)
head(Ramp_wl_fast_mat$SR.DAC.2.Lenkwinkel............................................)
tail(Ramp_wl_fast_mat$SR.DAC.2.Lenkwinkel............................................)